### ISSUE TITLE
UpperWastes/WindtornRuins spawn can only give you TP as progression

### ISSUE THREAD

**Issue by Foopyo** [ori-community/wotw-seedgen#26]
While paths using Burrow+Regenerate should let you get items when spawning at UpperWastes and WindtornRuins, seedgen prefer to give you a TP so you can progress from there instead.

On 10k seeds, getting burrow from the spawn items was only 2.45% likely at UpperWastes and 2.46% likely at WindtornRuins.
Regen is 22.24% at UpperWastes and 3.29% at WindtornRuins (this is especially weird since UpperWastes is supposed to require Regen and every area requiring regen as a 100% chance of giving it as a spawn item)
Wellspring TP is 36.31% at Upperwastes, 35.74% at WindtornRuins
Marsh TP is 60.98% at UpperWastes, 60.93% at WindtornRuins

[Position logic - OutsideRuins cumulative.pdf](https://github.com/ori-rando/wotw-seedgen/files/7945489/Position.logic.-.OutsideRuins.cumulative.pdf)
[Position logic - Ruins cumulative.pdf](https://github.com/ori-rando/wotw-seedgen/files/7945490/Position.logic.-.Ruins.cumulative.pdf)
[Position logic - EastWastes cumulative.pdf](https://github.com/ori-rando/wotw-seedgen/files/7945491/Position.logic.-.EastWastes.cumulative.pdf)

**Comment by Coder23848** [comment]
The lever door in Ruins prevents leaving through the entrance, so the only way to leave `WindtornRuins.RuinsTP` is to either teleport out (1 pickup) or complete the escape and then leave through the back door (minimum 4 pickups for moki, 3 for gorlek and above). If teleporters are disabled, the seedgen actually can't create a WindtornRuins seed for moki, since it can't give more than 3 spawn items.

This could be (partially) fixed by adding the lever door to the Better Random Spawn header.

**Comment by Coder23848** [comment]
Moki requires 5 Health Fragments and Regenerate to get items in UpperWastes, and there aren't enough spawn slots for that. Region requirements are apparently only needed for connections within the region; teleporters bypass them. This means that a teleporter will always be one of the spawn items. The same should be true for all regions with a health requirement.

In difficulties which only require Regenerate, Regenerate seems to not be chosen frequently because it unlocks exactly 0 items (you need Burrow as well) and the generator resolves region requirements before considering paths. In other words, the generator considers "Regenerate -> 0 pickups, Burrow -> many pickups", when it should really use "Regenerate+Burrow -> many pickups".

**Comment by Coder23848** [comment]
**Solution Ideas:**

- Add region requirements to paths instead of considering them separately
- Change number of spawn items based on the number of requirements used for outgoing paths
- Don't count region requirements against number of spawn items
- Set spawn items to be exactly what you need for a path, regardless of number

**Comment by SiriusAshling** [comment]
5ef05e2 fixes this, UpperWastes.NorthTP now spawns with Burrow in a majority of cases
